export const STORAGE_KEYS = {
  MAP: 'map',
  SITE: 'site',
  FEATURES: 'features',
  INTRO_DONE: 'isIntroDone',
  DEPLOYMENT: 'deployment',
  DEPLOYMENTS: 'deployments',
  PENDING_POST_KEY: 'pendingPost',
  PENDING_PROFILE_KEY: 'pendingProfilePhoto',
  COLLECTIONS: 'collections',
  PENDING_COLLECTIONS: 'pendingCollections',
  SURVEYS: 'surveys',
  POSTS: 'posts',
  GEOJSONPOSTS: 'geoJsonPosts',
  MAP_POSITION: 'mapPosition',
};
