export { SharedModule } from './shared.module';
export { TranslationsSwitchModule } from './components/translations-switch/translations-switch.module';
export { MainViewComponent } from './components/main-view.component';
export { LottieAnimationModule } from './components/lottie-animation/lottie-animation.module';
export { PasswordStrengthModule } from './components/password-strength/password-strength.module';
export { DirectiveModule } from './directive.module';
export { MapWithMarkerModule } from './components/map-with-marker/map-with-marker.module';
export { SpinnerModule } from './components/spinner/spinner.module';
export { PipeModule } from './pipe.module';
