const PostLocators = {
  addPostBtn: '[data-qa="submit-post-button"]',
  srvyItemBtn: '[data-qa="add-post-modal-surveys-item125"]',
  successButton: '[data-qa="btn-confirm-success"]',
  submitBtn: '[data-qa="btn-post-item-submit"]',
  postPreview: '[data-qa="post-preview"]',
  postItem: '[data-qa="post-item"]',
  surveySelectionList: '[data-qa="survey-selection-list"]',
  surveySelectItem: '[data-qa="survey-select-item125"]',
  confirmContent: '[data-qa="confirm-content"]',
  locationSearchField: '[data-qa="location-search"]',
  locationValues: '[data-qa="postLocationValues"]',

  /* Input fields */
  titleField: '[ng-reflect-data-qa="title"]',
  descField: '[data-qa="description"]',
  shtTextField: '[ng-reflect-data-qa="short-text field"]',
  lngTextField: '[data-qa="long-text field"]',
  decimalField: '[ng-reflect-data-qa="number-decimal field"]',
  intField: '[ng-reflect-data-qa="number-integer field"]',
  dateField: '[ng-reflect-data-qa="date-field"]',
  locationSearchField: '[data-qa="location-search"]',
  locationLatField: '[data-qa="location-lat"]',
  locationLongField: '[data-qa="location-lng"]',
  selectFieldBtn: '[data-qa="post-item-post-selectc5394e60-350d-4948-af81-6e8bf0502761"]',
  selectFieldOption1: '[data-qa="post-item-post-select-optionS1"]',
  radioFieldOption2: '[data-qa="radio-buttons-field-r2"]',
  checkboxFieldOption3: '[data-qa="checkboxes-field-f3"]',
  relatedPostField: '[data-qa="related-post-field"]',
  embedVideoField: '[data-qa="embed-video field"]',
  publishPostBtn: '[data-qa="btn-publish-post"]',
  postMenuDots: '[data-qa="post-menu"]',
  postStatus: '[data-qa="status"]',
  underReviewPostBtn: '[data-qa="btn-underReview-post"]',
  archivePostBtn: '[data-qa="btn-archive-post"]',
};

export default PostLocators;
