const CategoryLocators = {
  dataViewBtn: '[data-qa="btn-data"]',
  categoryFilterBtn: '[data-qa="categories-filter"]',
  stngsBtn: '[data-qa="btn-settings"]',
  surveyBtn: '[data-qa="btn-surveys"]',
  ctgryBtn: '[data-qa="btn-categories"]',
  addCategoryBtn: '[data-qa="btn-settings-create"]',
  blkActionsBtn: '[data-qa="btn-settings-action"]',
  deleteBtn: '[data-qa="btn-settings-delete"]',
  confirmdeleteBtn: '[data-qa="btn-confirm-delete"]',
  ctgryNameField: '[data-qa="name"]',
  ctgryDescField: '[data-qa="description"]',
  saveCtgryBtn: '[data-qa="btn-category-save"]',
  selectParentCtgry: '[data-qa="select-parent-category"]',
  everyoneRadio: '[data-qa="everyone"]',
  specificRolesRadioOption: '[data-qa="specific-roles..."]',
  translationCheckbox: '[data-qa="translation"]',
  technologyCheckbox: '[data-qa="technology"]',
  adminCheckbox: '[data-qa="admin"]',
  surveySelectItem: '[data-qa="add-post-modal-surveys-item188"]',
  addSurveyBtn: '[data-qa="btn-settings-create"]',
  postTitleField: '[data-qa="title"]',
  postDescField: '[data-qa="description"]',
  savePostBtn: '[data-qa="btn-post-item-submit"]',
  addPostBtn: '[data-qa="submit-post-button"]',
  successBtn: '[data-qa="btn-confirm-success"]',
  postPreview: '[data-qa="post-preview"]',
  postItem: '[data-qa="post-item"]',
  categoryDeleteBtn: '[data-qa="btn-category-delete"]',
  toggleChildrenBtn: '[data-qa="toggle-children"]',
};

export const getUniqueSelector = (name) => name.split(' ').join('-').toLowerCase();

export default CategoryLocators;
