const CollectionLocators = {
  collectionBtn: '[data-qa="btn-collections"]',
  addcollectionBtn: '[data-qa="add-collection"]',
  collectionNameField: '[data-qa="name"]',
  collectionDescField: '[data-qa="description"]',
  onlyMeRadio: '[data-qa="only-me"]',
  saveCollectionBtn: '[data-qa="save-collection-btn"]',
  selectCollection: '[data-qa="collection-item270"]',
  collectionCheckbox: '[data-qa="collection-item-checkbox"]',
  surveyItem: '[data-qa="add-post-modal-surveys-item2"]',
  submitPostButton: '[data-qa="submit-post-button"]',
  surveySelectionList: '[data-qa="survey-selection-list"]',
  selectedSurveyItem: '[data-qa="survey-select-item2"]',
  postTitleField: '[data-qa="null"]',
  postDescField: '[data-qa="description"]',
  postCheckBox: '[data-qa="nature-of-this-incident-failure-to-announce-results-by-iebc-officials"]',
  savePostBtn: '[data-qa="btn-post-item-submit"]',
  successBtn: '[data-qa="btn-confirm-success"]',
  surveySelectionList: '[data-qa="survey-selection-list"]',
  surveySelectItem: '[data-qa="survey-select-item2"]',
  addPostButton: '[data-qa="submit-post-button"]',
  saveCollectionButton: '[data-qa="save-collection-btn"]',
  collectionItem: '[data-qa="collection-item270"]',
  visibilityOption: '[data-qa="option"]',
  postItem: '[data-qa="post-item"]',
  morePostActionsBtn: '[data-qa="more-post-actions"]',
  addCollectionToPostCheckbox: '[data-qa="add-collection-to-post"]',
  closeCollectionModalBtn: '[data-qa="btn-close"]',
  dataViewBtn: '[data-qa="btn-data"]',
  postPreview: '[data-qa="post-preview"]',
  postItem: '[data-qa="post-item"]',
};

export default CollectionLocators;
