const DataViewLocators = {
  dataViewBtn: '[data-qa="btn-data"]',
  posts: '[data-qa="posts"]',
  surveySelectionList: '[data-qa="survey-selection-list"]',
  surveySelectItem: '[data-qa="survey-select-item"]',
  postPreview: '[data-qa="post-preview"]',
  postItem: '[data-qa="post-item"]',
  feedPageResults: '[data-qa="feed-page-results"]',
  mainResultsTotal: '[data-qa="search-form-main-filters-total"]',
  clearBtn: '[data-qa="clear"]',
  revealFiltersBtn: '[data-qa="search-form__filters"]',
  clearFiltersBtn: '[data-qa="search-form__button"]',
  statusBtn: '[data-qa="status"]',
  filterSelectionList: '[data-qa="filter-selection-list"]',
  filterListOption: '[data-qa="filter-list-option"]',
  addPostBtn: '[data-qa="submit-post-button"]',
  postTitleField: '[data-qa="title"]',
  postDescField: '[data-qa="description"]',
  savePostBtn: '[data-qa="btn-post-item-submit"]',
  successBtn: '[data-qa="btn-confirm-success"]',
  postPreview: '[data-qa="post-preview"]',
  postItem: '[data-qa="post-item"]',
  postMenuDots: '[data-qa="post-menu"]',
  deletePostBtn: '[data-qa="btn-delete-post"]',
  surveyToSubmitPost: '[data-qa="add-post-modal-surveys-item527"]',
  deleteConfirmBtn: '[data-qa="btn-confirm-delete"]',
};

export default DataViewLocators;
