const GeneralSettingsLocator = {
  deploymentNameField: '[data-qa="name"]',
  descriptionField: '[data-qa="description"]',
  apiKeyField: '[data-qa="api_key"]',
  saveButton: '[data-qa="btn-save"]',
  cancelButton: '[data-qa="btn-cancel"]',
  apiKeyCopyButton: '[data-qa="api-key-copy"]',
  settingsBtn: '[data-qa="btn-settings"]',
  disableUserSignupCheckbox: '[data-qa="site-disable-registration"] input',
  modalTabs: '[role="tab"]',
  panelTitle: '[data-qa="panel-title"]',
  generalBtn: '[data-qa="btn-general"]',
  privateCheckbox: '[data-qa="site-private"]',
  privateCheckboxCheck: '[data-qa="site-private"] input',
  logoutBtn: '[data-qa="log-out"]',
  denialMsg: '[data-qa="denied"]',
  contactEmail: '[data-qa="contact-email"]',
  emailField: '[data-qa="email"]',
  deleteImageBtn: '[data-qa="btn-update-logo"]',
  deploymentLogo: '[data-qa="deployment_logo"]',
  generateAPIKeyBtn: '[data-qa="generate-api-key"]',
  acceptGenerateAPIKeyBtn: '[data-qa="btn-confirm-delete"]',
  queryLocationField: '[data-qa="query-location"]',
  geocoderList: '[data-qa="geocoder-list"]',
  geocoderListItem: '[data-qa="geocoder-list-item"]',
  defaultLatitudeField: '[data-qa="default-latitude"]',
  defaultLongitudeField: '[data-qa="default-longitude"]',
};

export default GeneralSettingsLocator;
