const SurveyConfigurationLocators = {
  surveyList: '[data-qa="survey-list"]',
  configurationTestSurvey: '[data-qa="full-length-survey-with-image-field--don\'t-delete"]',
  survey: '[data-qa="counting-and-results"]',
  saveSurveyBtn: '[data-qa="btn-save-survey-item"]',
  settingsBtn: '[data-qa="btn-settings"]',
  surveyBtn: '[data-qa="btn-surveys"]',
  addPostBtn: '[data-qa="submit-post-button"]',
  postTitleField: '[ng-reflect-data-qa="title"]',
  postDescField: '[data-qa="description"]',
  postNumField: '[data-qa="null"]',
  postCheckBox: '[data-qa="checkboxes-field-f1"]',
  savePostBtn: '[data-qa="btn-post-item-submit"]',
  successBtn: '[data-qa="btn-confirm-success"]',
  postPreview: '[data-qa="post-preview"]',
  postItem: '[data-qa="post-item"]',
  clearBtn: '[data-qa="clear"]',
  postDate: '[data-qa="post-date"]',
  surveyItemBtn: '[data-qa="automation-survey---to-test-survey-configuration"]',
  surveySelectionList: '[data-qa="survey-selection-list"]',
  surveyToSubmit: '[data-qa="add-post-modal-surveys-item125"]',
  surveyToVerify: '[data-qa="survey-select-item125"]',
  postStatus: '[data-qa="status"]',
  reviewRqrdTgl: '[data-qa="toggle-posts-require-review"]',
  hideAuthorTgl: '[data-qa="toggle-hide-author"]',
  hideLocationTgl: '[data-qa="toggle-hide-location"]',
  hideTimeTgl: '[data-qa="toggle-hide-time"]',
  mapBtn: '[data-qa="btn-map"]',
  queryLocationSearchField: '[data-qa="location-search"]',
};

export default SurveyConfigurationLocators;
