const SurveyConfigurationLocators = {
  surveyList: '[data-qa="survey-list"]',
  saveSurveyBtn: '[data-qa="btn-save-survey-item"]',
  settingsBtn: '[data-qa="btn-settings"]',
  surveyBtn: '[data-qa="btn-surveys"]',
  addPostBtn: '[data-qa="submit-post-button"]',
  postTitleField: '[data-qa="title"]',
  postDescField: '[data-qa="description"]',
  savePostBtn: '[data-qa="btn-post-item-submit"]',
  successBtn: '[data-qa="btn-confirm-success"]',
  postPreview: '[data-qa="post-preview"]',
  postItem: '[data-qa="post-item"]',
  clearBtn: '[data-qa="clear"]',
  postDate: '[data-qa="post-date"]',
  surveyToConfigure: '[data-qa="automation-survey---to-test-survey-configuration"]',
  surveySelectionList: '[data-qa="survey-selection-list"]',
  surveyToSubmitPost: '[data-qa="add-post-modal-surveys-item527"]',
  surveyToVerify: '[data-qa="survey-select-item527"]',
  postStatus: '[data-qa="status"]',
  reviewRqrdTgl: '[data-qa="toggle-posts-require-review"]',
  hideAuthorTgl: '[data-qa="toggle-hide-author"]',
  hideLocationTgl: '[data-qa="toggle-hide-location"]',
  hideTimeTgl: '[data-qa="toggle-hide-time"]',
  mapBtn: '[data-qa="btn-map"]',
  queryLocationSearchField: '[data-qa="location-search"]',
};

export default SurveyConfigurationLocators;
